baseURL = "https://ctroupin.github.io/run"
languageCode = "en-us"
title = "Every kilometer counts!"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Charles Troupin - All rights reserved"
enableEmoji = true
publishDir = "docs"

[params]
  logo = "logo.png"
  description ="Ils ne savaient pas que c'était impossible alors ils l'ont fait"

[params.author]
  name = "Charles Troupin"
  thumbnail = "author.jpg"
  #description = "Creator of this blog."

[params.index]
  picture = "author.jpg"
  title = "Charles Troupin"
  subtitle = ""
  mdtext = '''  
  Every kilometer counts!       
  Chaque kilomètre compte!      
  Cada kilómetro cuenta!             

'''


  alertbar = false

[params.social]
  github = "ctroupin"
  gitlab = "ctroupin"
  twitter = "CharlesTroupin"
  flickr = "sharlo1982"
  a500px = "CharlesTroupin"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Races"
    weight = 200
    identifier = "races"
    url = "/races"
[[menu.main]]
    name = "City running"
    identifier = "city"
    weight = 400
    url = "/cityrunning"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 500
    url = "/about"
